version: '3.1'

services:
    mongo:
        image: 'mongo:4.2'
        hostname: 'mongodb'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ze_password
        ports:
            - 27017:27017
    # tool to visualise mongoDB ( web ui)
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: ze_password
